blueprint:
  name: Zero Effort Feeding Utility and Regulator (ZEFUR)
  description: Calculates daily feeding requirements based on pet weight, divides this into optimal portions based on serving size, and determines the best number of meals to closely match these portions.
  domain: automation
  input:
    pet_weight:
      name: Pet Weight
      description: Enter the weight of your pet in pounds.
      selector:
        entity:
          domain: input_number
    food_per_pound:
      name: Food per Pound
      description: Enter the amount of food in grams per pound of pet weight.
      selector:
        number:
          min: 1.0
          max: 100.0
          step: .01
          unit_of_measurement: "g"
    base_food:
      name: Base Food
      description: The amount of food to feed a hypothetical 0-weight pet. This value is used along with the 'Food per Pound' value to calculate how much food the pet should receive each day.
      selector:
        number:
          min: 0.0
          max: 50.0
          step: .01
          unit_of_measurement: "g"
    serving_size:
      name: Serving Size
      description: Enter the size of one serving of food in grams.
      selector:
        number:
          min: 1.0
          max: 100.0
          step: .05
          unit_of_measurement: "g"
    maximum_meals:
      name: Maximum Meals
      description: The maximum number of meals you want to feed in a day.
      selector:
        number:
          min: 2
          max: 50
          initial: 10

trigger:
  platform: state
  entity_id: input_number.pet_weight

action:
  - variables:
      weight: "{{ states('input_number.pet_weight') | float }}"
      food_per_lb: "{{ states('input_number.food_per_pound') | float }}"
      base_food: "{{ states('input_number.base_food') | float }}"
      serving: "{{ states('input_number.serving_size') | float }}"
      total_food: "{{ (weight * food_per_lb + base_food) | round(2) }}"
      total_portions: "{{ (total_food / serving) | round(0) }}"
      portions_per_meal: "{{ (total_food / meals_per_day) | round(2) }}"
      optimal_meals: 1
      meals_per_day: >-
        {% set possible_meals = range(1, 10) | map('int') %}
        {% set meal_ratios = possible_meals | map(attribute='__div__', other=total_portions) %}
        {% set closest_meal = meal_ratios | min %}
        {{ closest_meal }}
  - repeat:
      while:
        - "{{ current_meals <= maximum_meals }}"
      sequence:
        - variables:
            portions_per_meal: "{{ (total_food / current_meals) | round(2) }}"
            remainder: "{{ total_portions % current_meals }}"
        - choose:
            - conditions: "{{ remainder < smallest_remainder }}"
              sequence:
                - variables:
                    smallest_remainder: "{{ remainder }}"
                    optimal_meals: "{{ current_meals }}"
        - variables:
            current_meals: "{{ current_meals + 1 }}"
      until:
        - "{{ current_meals > maximum_meals }}"
